# Using the terraform cloud for the purpose of managing the status.

stages:
  - deploy

deploy:
  image: 
    name: stashconsulting/terraform-docker:gcloud-latest
    entrypoint: [""]
  stage: deploy
  script:
    - gcloud auth configure-docker
    - terraform --version
    - echo $token | terraform login
    - terraform init
    - terraform apply -auto-approve -var image_id=$image -var project=$project || echo "failure"
  tags:
    - docker_image
