stages:
  - deploy

deploy:
  image: 
    name: stashconsulting/terraform-docker:gcloud-latest
    entrypoint: [""]
  stage: deploy
  script:
    - gcloud auth configure-docker
    - terraform init
    - gsutil rsync gs://tfstatebackup2 .
    - terraform apply -auto-approve -var image_id=$image -var project=$project || echo "failure"
  tags:
    - docker_image
