stages:
  - prepare
  - deploy

prepare:
  image: alpine
  stage: prepare
  script:
    - echo -n $service_account > credentials.json
  artifacts:
    paths:
      - credentials.json
  tags:
    - docker_image

deploy:
  image: 
    name: stashconsulting/terraform-docker:gcloud-latest
    entrypoint: [""]
  stage: deploy
  script:
    - gcloud auth activate-service-account --key-file credentials.json
    - gcloud auth configure-docker
    - terraform init
    - terraform apply -auto-approve -var image_id=$image -var project=$project
  tags:
    - docker_image
