steps:
# Fetch the source code
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/stashconsulting/cloudstorage-rssfeed-python-cloudfunction.git']

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kong_dbless:$SHORT_SHA', '.']

# This step pushes the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'gcr.io/$PROJECT_ID/kong_dbless:$SHORT_SHA']

# Using public terraform Docker image
- name: hashicorp/terraform
  args: ['init']

# Copy the results from the Google Cloud Storage bucket
- name: gcr.io/cloud-builders/gsutil
  id: copy-result
  args: ['cp', 'gs://tfstatebackup/*', '.']

# Create the resources using Terraform
- name: hashicorp/terraform
  id: terraform-apply
  entrypoint: 'sh'
  args: 
  - '-c'
  - terraform apply -auto-approve -var image_id=gcr.io/$PROJECT_ID/kong_dbless:$SHORT_SHA 

# Copy the new results back into the bucket.
- name: gcr.io/cloud-builders/gsutil
  id: put-result
  args: ['cp', '-r', 'terraform.tfstate*', 'gs://tfstatebackup/']
