swagger: '2.0'
info:
  title: Upload a file to bucket and save respective information on firestore
  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: ${cloud_run_hostname}
schemes:
  - https
  - http
produces:
  - application/json
paths:
  /insertData:
    post:
      summary: "Add a new file to the collection"
      operationId: "saveinfo"
      x-google-backend:
        address: ${inserdata_functionurl} 
      consumes:
        - multipart/form-data
      parameters:
        - name: title
          in: formData
          required: true
          type: string
          description: "Save text"
        - name: description
          in: formData
          required: true
          type: string
          description: "Save text"
        - name: creation_date
          in: formData
          required: true
          type: string
          format: "date-time"
          description: "Save date"
        - name: _file
          in: formData
          required: true
          type: string
          description: "The file to upload"
      responses:
        200:
          description: "Success"
        204:
          description: "No content"
        400:
          description: "Bad request"
        404:
          description: "Not found"
        405:
          description: "Invalid input"
        406:
          description: "Not aceptable"
        408:
          description: "Request timeout"
        409:
          description: "Conflict"
        410:
          description: "Gone"
        415:
          description: "Unsupported Media Type"
        421:
          description: "Misdirected Request"
        429:
          description: "Too Many Requests" 
  /getJson:
    get:
      summary: shown xml file inside the bucket in json
      operationId: convert
      x-google-backend:
        address: ${getjson_functionurl}
      responses:
        200:
          description: "Success"
        204:
          description: "No content"
        400:
          description: "Bad request"
        404:
          description: "Not found"
        405:
          description: "Invalid input"
        406:
          description: "Not aceptable"
        408:
          description: "Request timeout"
        409:
          description: "Conflict"
        410:
          description: "Gone"
        415:
          description: "Unsupported Media Type"
        421:
          description: "Misdirected Request"
        429:
          description: "Too Many Requests"
          schema:
            type: string      
